export const environment = {
  registerUrl: 'http://localhost:3000/register',
  loginUrl: 'http://localhost:3000/login',
  userUrl: 'http://localhost:3000/users',
  apartmentsUrl: 'https://671f5051e7a5792f052dcafa.mockapi.io/apartments',
  favouritesUrl: 'https://671f5051e7a5792f052dcafa.mockapi.io/favourites',
  messageUrl: 'https://672142fe98bbb4d93ca7f8e6.mockapi.io/messages',
  logo: 'https://images-ext-1.discordapp.net/external/jD0Gjp_45OhK5u15FOSEH_GYXcbKycyJf-q1SqHzCQs/https/upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_B%25C3%25A9lo.svg/1200px-Airbnb_Logo_B%25C3%25A9lo.svg.png?format=webp&quality=lossless&width=1114&height=348',
  firebaseConfig: {
    apiKey: 'AIzaSyBwLbFZlLUK-WilUmCW1iAIxbFFqHch7E4',
    authDomain: 'buildweek-82174.firebaseapp.com',
    projectId: 'buildweek-82174',
    storageBucket: 'buildweek-82174.appspot.com',
    messagingSenderId: '570121466914',
    appId: '1:570121466914:web:255a5ba05c47d75654067b',
  },
  services: [
    { service: 'WiFi', icon: 'ionWifiOutline' },
    { service: 'Aria condizionata', icon: 'ionSnowOutline' },
    { service: 'Riscaldamento', icon: 'ionFlameOutline' },
    { service: 'TV', icon: 'ionTvOutline' },
    { service: 'Lavatrice', icon: 'ionShirtOutline' },
    { service: 'Asciugatrice', icon: 'matLocalLaundryService' },
    { service: 'Cucina attrezzata', icon: 'matBlender' },
    { service: 'Frigorifero', icon: 'matKitchen' },
    { service: 'Microonde', icon: 'matMicrowave' },
    { service: 'Macchina del caffè', icon: 'ionCafeOutline' },
    { service: 'Asciugamani inclusi', icon: 'ionHandLeftOutline' },
    { service: 'Parcheggio gratuito', icon: 'ionCarOutline' },
    { service: 'Piscina', icon: 'ionWaterOutline' },
    { service: 'Palestra', icon: 'ionFootballOutline' },
    { service: 'Area barbecue', icon: 'ionBonfireOutline' },
    { service: 'Balcone o terrazza', icon: 'matBalcony' },
    { service: 'Giardino', icon: 'ionRoseOutline' },
    { service: 'Accesso per disabili', icon: 'ionBodyOutline' },
    { service: 'Animali ammessi', icon: 'matPets' },
    { service: 'Vasca idromassaggio', icon: 'matWaves' },
    { service: 'Servizio di pulizia', icon: 'matCleaningServices' },
    { service: 'Reception 24 ore', icon: 'matHelpCenter' },
    { service: 'Vista panoramica', icon: 'matLandscape' },
    { service: 'Servizio in camera', icon: 'matRoomService' },
    { service: 'Minibar', icon: 'matLocalBar' },
    { service: 'Colazione inclusa', icon: 'matBakeryDining' },
  ],
  categories: [
    'spiaggia',
    'famiglia',
    'città',
    'lusso',
    'natura',
    'romantico',
    'campagna',
    'modernità',
    'lago',
    'gruppi',
    'romantico',
  ],
};
